# .github/workflows/test-parallel.yml
name: Test (parallel) -Chrome_Firefox_edge

on: [workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:16

    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox']

    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install libraries
        run: npm install 
        timeout-minutes: 10
        
      - name: Run Tests
        continue-on-error: true
        run:  npm test   
      
#       - uses: everlytic/branch-merge@1.1.2
#         with:          
#           source_ref: 'qa'
#           target_branch: 'uat'
#           commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'       
        
      - name: Generate report
        uses: actions/upload-artifact@v2
        with:
         name: QA-report.html
         path: "**/cucumber-report.html"     
     
        env:
          BROWSER: ${{ matrix.browser }}        
     
